### ISSUE TITLE
Lua Error with TradeSkillMaster addon

### ISSUE THREAD

**Issue by icozha** [Kkthnx/KkthnxUI_Legion#133]
Message: Interface\AddOns\KkthnxUI\Modules\Inventory\Bags.lua:447: attempt to index field 'Reagent' (a nil value)
Time: 01/24/17 21:39:52
Count: 1
Stack: ...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
Interface\AddOns\KkthnxUI\Modules\Inventory\Bags.lua:447: in function <Interface\AddOns\KkthnxUI\Modules\Inventory\Bags.lua:440>

Locals: errMsg = "Interface\AddOns\KkthnxUI\Modules\Inventory\Bags.lua:447: attempt to index field 'Reagent' (a nil value)"
isTSMError = false
tsmErrMsg = nil
AceGUI = <table> {
 objPools = <table> {
 }
 RegisterAsContainer = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:521
 RegisterWidgetType = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:559
 WidgetBase = <table> {
 }
 RegisterAsWidget = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:537
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 GetLayout = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:583
 GetWidgetVersion = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:613
 Create = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:172
 GetWidgetCount = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:607
 GetNextWidgetNum = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:596
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 RegisterLayout = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:573
 Release = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:206
 ClearFocus = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:257
 WidgetContainerBase = <table> {
 }
 SetFocus = <function> defined @Interface\AddOns\TradeSkillMaster\Libs\AceGUI-3.0\AceGUI-3.0.lua:247
}
TSM = <table> {
 Operations = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\KkthnxUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:398
 _author = "Sapu94, Bart39"
 DeleteCustomPriceSource = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Prices.lua:56
 EnableModule = <function> defined @Interface\AddOns\KkthnxUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "TradeSkillMaster"
 IterateEmbeds = <function> defined @Interface\AddOns\KkthnxUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:473
 CreateGroupTree = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\TSMFrames\GroupTree.lua:291
 SecureHookScript = <function> defined @Interface\AddOns\KkthnxUI\Libraries\AceHook-3.0\AceHook-3.0.lua:410
 GetAuctionPlayer = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\AuctionFrame.lua:45
 RawHookScript = <function> defined @Interface\AddOns\KkthnxUI\Libraries\AceHook-3.0\AceHook-3.0.lua:395
 _desc = "Core addon for the TradeSkillMaster suite. Does nothing without modules installed."
 Printf = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Modules.lua:147
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\KkthnxUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:440
 NO_SOUND_KEY = "TSM_NO_SOUND"
 LDBIcon = <table> {
 }
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\KkthnxUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:482
 LOG_INFO = <function> defined @Interface\AddOns\TradeSkillMaster\Debug\Logging.lua:376
 Delay = <table> {
 }
 OnTSMDBShutdown = <function> defined @Interface\AddOns\TradeSkillMaster\TradeSkillMaster.lua:409
 operations = <table> {
 }
 RegisterModule = <function> defined @Interface\AddOns\TradeSkillMaster\TradeSkillMaster.lua:337
 toggleBankUI = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\BankUI.lua:307
 ShowConfigError = <function> defined

**Comment by Kkthnx** [comment]
Not my problem. TSM hooks into the bags. He needs to fix this on his end. Thank you for the report though.

**Comment by icozha** [comment]
[22:25] -Q- [#TradeSkillMaster] IRC Rules: Don't ask to ask. Don't ask if anybody's around. Just ask your question.
[22:26] <icozha> hey all, lua error http://pastebin.com/jLcjjSwZ
[22:27] <@Gumdrops> That's not a TSM error
[22:27] <@Gumdrops> Seems like a problem with KkthnxUI
[22:29] <icozha> y, pls check this https://github.com/Kkthnx/KkthnxUI_Legion/issues/133
[22:29] <@Gumdrops> That's not a TSM error though, just TSM displaying it, the problem is on their side
[22:30] <@Gumdrops> isTSMError = false
[22:31] <icozha> thx for reply

**Comment by Kkthnx** [comment]
Lol, He hooks directly into the blizzard bags. Correct me if I am wrong. I don't see how I would fix this issue.

**Comment by Kkthnx** [comment]
@Epsynus Really no need for you to come and thumbs down my posts. 🗡 

@icozha please let me know if the issue has been solved.

**Comment by Epsynus** [comment]
@Kkthnx The feature is there to voice that I dislike your attitude towards the issue at hand, as it was basically you shrugging at the person taking no responsibility for the error, instead just doing a back and forth throw with the TSM crew. While I do see that you now have made an attempt to fix the issue, which is good. What I do think you need to do is improve your attitude towards your userbase.

**Comment by Kkthnx** [comment]
I had no attitude at all. Believe me when I say this, but my user base
knows how well I keep them informed and listen every single day as I deal
with 60 or more or my users daily in my discord. You cant judge someone off
of one mistake and that is what you are doing currently.

**Comment by Epsynus** [comment]
While I do think that this discussion has had no place to begin with inside of an issue report what I will do is simply just give this reply, turn off notifications and move on and we can take the discussion to another place if you so desire.

However what I want to make clear is that this isn't me judging you based off of one mistake, I have been following your github for several months, watching all issue reports and updates, and doing this simply because while I do not agree with how your attitude is at certain times, I do think your coding is clean and I learn from it.

With that said, I have also been in your Discord since around the time you made it public and there has been plenty of times where your attitude towards an issue is very..how to put it...Rude and unnecessary. 

While of course you can't expect a person to always be happy and shit, of course slipups happen when you might be tired or something else is bother you in your personal life or whatever, you are human and I do not fault you for that, however I am within my right to voice my dissent and have my own opinion in regards to how you at times handle situations, and that is not an opinion that I formed simply based on this single case, it has been formed through months of interaction.

I have to say though that I think that you not only acted a bit childish by removing your prior posts simply because I thumbed them down. I also have to say that I think you are escalating this far beyond what is necessary in this kind of a situation. 

In my opinion an alternative rather than saying "@Epsynus Really no need for you to come and thumbs down my posts. 🗡" would be
"I dislike that you come in here and thumbs down my posts without a clear reason as to why"
or
"If you have concerns or feedback please take it up with me on my Discord/E-mail/wherever else"

This would then show that you might not be happy about the tumbsdown without knowing exactly why they are there, and also the second option would show that you are very much open to constructive criticism and also allow it to be taken up in a more..appropriate place than on an issue report.

Now that said, it is entirely up to you how you wish to handle things and if you felt that this was the appropriate option then more power to you. 

All in all, I think this got blown up bigger than it was ever intended to be and I will simply not be replying to this again as I feel that there is nothing more that can be said.

Wish you all the best.

**Comment by Kkthnx** [comment]
@icozha I have placed a fix for this report, please let me know if any other issue arise.
